package com.github.piotr_rusin.algorithms.sorting

class InsertionSortWithSwapTest: SortTest(::sortByInsertionWithSwap)

class InsertionSortWithPushingPredecessorTest: SortTest(::sortByInsertionWithPushingPredecessor)

class RecursiveInsertionSortWithPushingPredecessorTest: SortTest(::recursivelySortByInsertionWithPushingPredecessor)
